"""Text normalization shared by grounding checks, dedup and report rendering.

The synthetic corpora generated by this toolkit are English, so the stopword
list and the negation cues are English too. Every function here is pure: no
mutable state, no locale dependence and no I/O.
"""

from __future__ import annotations

import re
import unicodedata

WHITESPACE_PATTERN = re.compile(r"\s+")


def normalize_whitespace(text: str) -> str:
    """Collapse every whitespace run to one space and strip the ends."""
    return WHITESPACE_PATTERN.sub(" ", text).strip()


def fold_accents(text: str) -> str:
    """Drop combining marks so that accented letters compare equal to ASCII ones.

    Characters that have no decomposition (for example CJK ideographs) are kept
    unchanged; this helper never deletes non-combining characters.
    """
    decomposed = unicodedata.normalize("NFKD", text)
    return "".join(char for char in decomposed if not unicodedata.combining(char))


PUNCTUATION_PATTERN = re.compile(r"[^\w\s]", re.UNICODE)


def strip_punctuation(text: str) -> str:
    """Replace punctuation with spaces so hyphenated compounds become tokens.

    ``"state-of-the-art"`` becomes ``"state of the art"``; the replacement is a
    space rather than nothing so that adjacent words are never merged.
    """
    return PUNCTUATION_PATTERN.sub(" ", text)


def normalize(
    text: str,
    *,
    lower: bool = True,
    remove_punctuation: bool = True,
    fold: bool = True,
    collapse_whitespace: bool = True,
) -> str:
    """Apply the standard normalization chain used across the toolkit.

    Order matters: accents are folded before case folding (``casefold`` expands
    ``ß`` to ``ss``), punctuation becomes spaces before whitespace collapsing so
    the result never contains double spaces.
    """
    result = text
    if fold:
        result = fold_accents(result)
    if lower:
        result = result.casefold()
    if remove_punctuation:
        result = strip_punctuation(result)
    if collapse_whitespace:
        result = normalize_whitespace(result)
    return result
