"""Text normalization shared by grounding checks, dedup and report rendering.

The synthetic corpora generated by this toolkit are English, so the stopword
list and the negation cues are English too. Every function here is pure: no
mutable state, no locale dependence and no I/O.
"""

from __future__ import annotations

import re
import unicodedata

WHITESPACE_PATTERN = re.compile(r"\s+")


def normalize_whitespace(text: str) -> str:
    """Collapse every whitespace run to one space and strip the ends."""
    return WHITESPACE_PATTERN.sub(" ", text).strip()


def fold_accents(text: str) -> str:
    """Drop combining marks so that accented letters compare equal to ASCII ones.

    Characters that have no decomposition (for example CJK ideographs) are kept
    unchanged; this helper never deletes non-combining characters.
    """
    decomposed = unicodedata.normalize("NFKD", text)
    return "".join(char for char in decomposed if not unicodedata.combining(char))
