"""Text normalization shared by grounding checks, dedup and report rendering.

The synthetic corpora generated by this toolkit are English, so the stopword
list and the negation cues are English too. Every function here is pure: no
mutable state, no locale dependence and no I/O.
"""

from __future__ import annotations

import re
import unicodedata
from collections.abc import Sequence

from hypoarena.errors import ValidationError

WHITESPACE_PATTERN = re.compile(r"\s+")


def normalize_whitespace(text: str) -> str:
    """Collapse every whitespace run to one space and strip the ends."""
    return WHITESPACE_PATTERN.sub(" ", text).strip()


def fold_accents(text: str) -> str:
    """Drop combining marks so that accented letters compare equal to ASCII ones.

    Characters that have no decomposition (for example CJK ideographs) are kept
    unchanged; this helper never deletes non-combining characters.
    """
    decomposed = unicodedata.normalize("NFKD", text)
    return "".join(char for char in decomposed if not unicodedata.combining(char))


PUNCTUATION_PATTERN = re.compile(r"[^\w\s]", re.UNICODE)


def strip_punctuation(text: str) -> str:
    """Replace punctuation with spaces so hyphenated compounds become tokens.

    ``"state-of-the-art"`` becomes ``"state of the art"``; the replacement is a
    space rather than nothing so that adjacent words are never merged.
    """
    return PUNCTUATION_PATTERN.sub(" ", text)


def normalize(
    text: str,
    *,
    lower: bool = True,
    remove_punctuation: bool = True,
    fold: bool = True,
    collapse_whitespace: bool = True,
) -> str:
    """Apply the standard normalization chain used across the toolkit.

    Order matters: accents are folded before case folding (``casefold`` expands
    ``ß`` to ``ss``), punctuation becomes spaces before whitespace collapsing so
    the result never contains double spaces.
    """
    result = text
    if fold:
        result = fold_accents(result)
    if lower:
        result = result.casefold()
    if remove_punctuation:
        result = strip_punctuation(result)
    if collapse_whitespace:
        result = normalize_whitespace(result)
    return result


WORD_PATTERN = re.compile(r"[a-z0-9]+")
STOPWORDS = frozenset(
    {
        "a",
        "about",
        "above",
        "after",
        "again",
        "all",
        "also",
        "am",
        "an",
        "and",
        "any",
        "are",
        "as",
        "at",
        "be",
        "because",
        "been",
        "before",
        "being",
        "below",
        "between",
        "both",
        "but",
        "by",
        "can",
        "could",
        "did",
        "do",
        "does",
        "doing",
        "down",
        "during",
        "each",
        "few",
        "for",
        "from",
        "further",
        "had",
        "has",
        "have",
        "having",
        "he",
        "her",
        "here",
        "hers",
        "him",
        "his",
        "how",
        "i",
        "if",
        "in",
        "into",
        "is",
        "it",
        "its",
        "itself",
        "just",
        "me",
        "more",
        "most",
        "my",
        "no",
        "nor",
        "not",
        "of",
        "off",
        "on",
        "once",
        "only",
        "or",
        "other",
        "our",
        "ours",
        "out",
        "over",
        "own",
        "same",
        "she",
        "should",
        "so",
        "some",
        "such",
        "than",
        "that",
        "the",
        "their",
        "theirs",
        "them",
        "then",
        "there",
        "these",
        "they",
        "this",
        "those",
        "through",
        "to",
        "too",
        "under",
        "until",
        "up",
        "very",
        "was",
        "we",
        "were",
        "what",
        "when",
        "where",
        "which",
        "while",
        "who",
        "whom",
        "why",
        "will",
        "with",
        "would",
        "you",
        "your",
        "yours",
    }
)


def tokenize(text: str) -> list[str]:
    """Split ``text`` into normalized alphanumeric tokens.

    Letters and digits stay joined, so ``"p53"`` is one token while ``"p-53"``
    becomes two (punctuation is replaced by a space first). Characters that are
    neither ASCII letters nor digits are dropped, which suits the English
    synthetic corpora this toolkit generates.
    """
    return WORD_PATTERN.findall(normalize(text))


def content_tokens(text: str) -> list[str]:
    """Return tokens with English stopwords removed, preserving order."""
    return [token for token in tokenize(text) if token not in STOPWORDS]


def char_ngrams(text: str, n: int) -> list[str]:
    """Return character n-grams of the normalized text with whitespace removed.

    Whitespace is dropped first so that reflowing a sentence does not change its
    shingles. Strings shorter than ``n`` yield the whole string as a single gram
    (and the empty string yields nothing), which keeps similarity measures
    defined for very short inputs.
    """
    if n < 1:
        raise ValidationError("n-gram size must be >= 1", n=n)
    compact = normalize(text).replace(" ", "")
    if not compact:
        return []
    if len(compact) < n:
        return [compact]
    return [compact[index : index + n] for index in range(len(compact) - n + 1)]


def word_ngrams(tokens: Sequence[str], n: int) -> list[str]:
    """Return word n-grams joined by single spaces.

    Mirrors :func:`char_ngrams` for short inputs: fewer tokens than ``n`` yields
    one gram holding all tokens, an empty sequence yields nothing.
    """
    if n < 1:
        raise ValidationError("n-gram size must be >= 1", n=n)
    words = list(tokens)
    if not words:
        return []
    if len(words) < n:
        return [" ".join(words)]
    return [" ".join(words[index : index + n]) for index in range(len(words) - n + 1)]
